apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kube-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-kube-app
  template:
    metadata:
      labels:
        app: node-kube-app
    spec:
      containers:
      - name: node-kube-container
        image: kema94/node-kube-app
        ports:
        - containerPort: 3000
