apiVersion: v1
kind: Service
metadata:
  name: node-kube-service
spec:
  type: NodePort
  selector:
    app: node-kube-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30035
